version: '3.5'

services:
 SSO:
  image: ${DOCKER_REGISTRY-}sso-$ASPNETCORE_ENVIRONMENT
  extra_hosts:
   - "host.docker.internal:host-gateway"
  environment:
   - Kestrel__CertPath=Certificates/certificate.pfx
   - ServerOptions__UseDevelopmentCertificates=true
   - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
   #- ServerOptions__IdentityDbConnectString=Data Source=tradeblotter.database.windows.net; Initial Catalog=IdentityDev; Integrated Security=False; User ID=tradeblotteradmin; Password=AliEgBilsol022; MultipleActiveResultSets=False
   #- ServerOptions__EncriptionSertificateThumbprint=Certificates/encryption-certificate.pfx
   #- ServerOptions__SigningSertificateThumbprint=Certificates/signing-certificate.pfx
  ports:
   - "5011:5011"
  volumes:
   - ~/.aspnet/https:/app/Certificates:ro